version: '3.8'

services:
  web:
    build: .
    ports:
      - "5500:5500"
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - SERVER_HOST
      - ENV=${ENV}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

  db_test:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

volumes:
  pgdata:
  pgdata_test:
